import requests from './request'
import mock from './mock'

export const reqCategoryList = () => requests({ url: '/product/getBaseCategoryList' })
export const reqGetBannerList = () => mock({ url: '/banners' })
export const reqGetFloorList = () => mock({ url: '/floors' })
export const reqMockAddress = () => mock({ url: '/address' })
export const reqGetSearchInfo = params => requests({ method: 'post', url: '/list', data: params })
export const reqGetDetailInfo = skuId => requests({ url: `/item/${skuId}` })
export const reqAddOrUpdateCart = (skuId, skuNum) => requests({ url: `/cart/addToCart/${skuId}/${skuNum}`, method: 'post' })
export const reqGetCartList = () => requests({ url: '/cart/cartList' })
export const reqDeleteCart = skuId => requests({ url: `/cart/deleteCart/${skuId}`, method: 'delete' })
export const reqUpdateChecked = (skuId, isChecked) => requests({ url: `/cart/checkCart/${skuId}/${isChecked}` })
export const reqSendCode = phone => requests({ url: `/user/passport/sendCode/${phone}` })
export const reqUserRegister = data => requests({ url: '/user/passport/register', method: 'post', data })
export const reqUserLogin = data => requests({ url: '/user/passport/login', method: 'post', data })
export const reqUserInfo = () => requests({ url: 'user/passport/auth/getUserInfo' })
export const reqUserLogout = () => requests({ url: '/user/passport/logout' })
export const reqAddressInfo = () => requests({ url: '/user/userAddress/auth/findUserAddressList' })
export const reqOrderInfo = () => requests({ url: '/order/auth/trade' })
export const reqSubmitOrder = (tradeNo, data) => requests({ url: `/order/auth/submitOrder?tradeNo=${tradeNo}`, data, method: 'post' })
export const reqPayInfo = orderId => requests({ url: `/payment/weixin/createNative/${orderId}` })
export const reqPayStatus = orderId => requests({ url: `/payment/weixin/queryPayStatus/${orderId}` })
export const reqUserOrder = (page, limit) => requests({ url: `/order/auth/${page}/${limit}` })